[window]
opacity = 0.9
padding.x = 5
padding.y = 5

[scrolling]
history = 100000
multiplier = 3

[font]
normal.family = "Comic Code"
bold.family = "Comic Code"
italic.family = "Comic Code"
bold_italic.family = "Comic Code"

size = 12.0

